# Generated by Django 3.1.3 on 2020-11-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photo_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/miniatura', verbose_name='Foto para miniatura'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='summary',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Resumen'),
        ),
    ]
