# Generated by Django 3.1.3 on 2020-11-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20201109_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogallery',
            name='url',
            field=models.URLField(blank=True, default='', max_length=150, null=True, verbose_name='Ids del video'),
        ),
    ]
