# Generated by Django 3.1.3 on 2020-11-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20201109_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videogallery',
            options={'verbose_name': 'Url del video para la galería', 'verbose_name_plural': 'Urls de los videos para la galería'},
        ),
        migrations.AlterField(
            model_name='videogallery',
            name='url',
            field=models.URLField(blank=True, default='', max_length=150, null=True, verbose_name='Url del video'),
        ),
    ]
