# Generated by Django 3.1.3 on 2020-11-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20201109_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='photo_thumbnail',
        ),
        migrations.AddField(
            model_name='gallery',
            name='photo_main',
            field=models.ImageField(blank=True, default='', null=True, upload_to='static/galeria/', verbose_name='Foto para miniatura'),
        ),
    ]
