# Generated by Django 3.1.3 on 2020-11-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20201109_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='summary',
        ),
        migrations.AddField(
            model_name='gallery',
            name='descent',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Bajada'),
        ),
    ]
