# Generated by Django 3.1.3 on 2020-11-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20201109_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photo_main',
            field=models.ImageField(blank=True, null=True, upload_to='static/galeria/', verbose_name='Foto para miniatura'),
        ),
        migrations.AlterField(
            model_name='videogallery',
            name='url',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Url del video'),
        ),
    ]
