# Generated by Django 3.1.3 on 2020-11-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20201112_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/galeria/video', verbose_name='Agregar fotografías'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/galeria/imagen', verbose_name='Agregar fotografías'),
        ),
    ]
