# Generated by Django 3.1.3 on 2020-11-16 03:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0002_auto_20201108_2100'),
        ('category', '0004_auto_20201111_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('descent', models.TextField(blank=True, max_length=500, null=True, verbose_name='Bajada')),
                ('photo_main', models.ImageField(blank=True, null=True, upload_to='static/agenda/', verbose_name='Foto para miniatura')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacción')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author', verbose_name='Autor')),
                ('category', models.ManyToManyField(to='category.Category', verbose_name='Categorías')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'ordering': ['-created'],
            },
        ),
    ]
