# Generated by Django 3.1.3 on 2020-11-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='photo_main',
            field=models.ImageField(blank=True, null=True, upload_to='agenda', verbose_name='Foto para miniatura'),
        ),
    ]
