# Generated by Django 3.1.3 on 2020-11-25 18:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20201119_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='descent',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True, verbose_name='Bajada'),
        ),
    ]
