# Generated by Django 3.1.3 on 2020-11-20 01:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0002_auto_20201108_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ultimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('photo_main', models.ImageField(blank=True, null=True, upload_to='ultimas', verbose_name='Foto para miniatura')),
                ('url', models.URLField(verbose_name='Ingresa el Url')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacción')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author', verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Última noticia',
                'verbose_name_plural': 'Últimas noticias',
                'ordering': ['-created'],
            },
        ),
    ]
