# Generated by Django 3.1.3 on 2020-11-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique=True, verbose_name='Slug'),
        ),
    ]
