# Generated by Django 3.1.3 on 2020-11-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20201108_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo_thumbnail',
            field=models.ImageField(blank=True, default='', null=True, upload_to='articulo/miniatura', verbose_name='Foto para miniatura'),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo_main',
            field=models.ImageField(blank=True, null=True, upload_to='articulo', verbose_name='Foto de portada'),
        ),
    ]
