# Generated by Django 3.1.3 on 2020-11-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20201109_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='photo_thumbnail',
        ),
        migrations.AlterField(
            model_name='article',
            name='photo_main',
            field=models.ImageField(blank=True, null=True, upload_to='static/articulo', verbose_name='Foto de portada'),
        ),
    ]
