# Generated by Django 3.1.3 on 2020-11-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20201109_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(default='', max_length=250, verbose_name='Fuente'),
        ),
    ]
