# Generated by Django 3.1.3 on 2020-11-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20201111_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo_main',
            field=models.ImageField(blank=True, null=True, upload_to='articulo', verbose_name='Foto de portada'),
        ),
    ]
