# Generated by Django 3.1.3 on 2020-11-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Primer nombre')),
                ('last_name', models.CharField(max_length=255, verbose_name='Segundo nombre')),
                ('lastname', models.CharField(max_length=255, verbose_name='Apellido paterno')),
                ('lastname1', models.CharField(max_length=255, verbose_name='Apellido materno')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacción')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['-created'],
            },
        ),
    ]
