# Generated by Django 3.1.3 on 2020-11-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='author',
            name='lastname1',
        ),
        migrations.AddField(
            model_name='author',
            name='last_name1',
            field=models.CharField(default='', max_length=255, verbose_name='Apellido materno'),
        ),
        migrations.AddField(
            model_name='author',
            name='second_name',
            field=models.CharField(default='', max_length=255, verbose_name='Segundo nombre'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(default='', max_length=255, verbose_name='Apellido paterno'),
        ),
    ]
