# Generated by Django 3.1.3 on 2020-11-15 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_auto_20201115_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='url',
        ),
    ]
