# Generated by Django 3.1.3 on 2020-11-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0003_remove_forum_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='photo_main',
            field=models.ImageField(blank=True, null=True, upload_to='foro', verbose_name='Foto para miniatura'),
        ),
    ]
